title: Comprehensive Guide to Transformers for Computer Vision Engineers
description: A comprehensive guide covering transformer theory and applications in computer vision
theme: jekyll-theme-cayman
baseurl: "/Comprehensive-Guide-to-Transformers-for-CV"
url: "https://trietvo3105.github.io"
github:
    is_project_page: true
    repository_url: https://github.com/trietvo3105/Comprehensive-Guide-to-Transformers-for-CV
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
plugins:
    - jekyll-feed
    - jekyll-seo-tag

# GitHub Pages specific settings
github_username: trietvo3105
repository: trietvo3105/Comprehensive-Guide-to-Transformers-for-CV

# Build settings
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
    noscript: false

# Exclude from processing
exclude:
    - "Transformer Theory for Computer Vision.md"
    - "Transformer Applications in Computer Vision.md"
    - "Setup Instructions for Vision Transformer Hands-on Practice.md"
    - "Hands-on Practice with Vision Transformers.md"
    - "Comprehensive Lecture on Transformers for Computer Vision.md"
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor
    - .sass-cache/
    - .jekyll-cache/
    - .bundle/
    - build-local.sh
