name: Build and deploy Jekyll site to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.1"
                  bundler-cache: true

            - name: Build and deploy
              uses: jeffreytse/jekyll-deploy-action@v0.5.0
              with:
                  provider: "github"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: "gh-pages"
                  jekyll_src: "./"
                  jekyll_cfg: "_config.yml"
                  cname: ""
