name: Simple Jekyll Build

on:
    push:
        branches: [main, master]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  persist-credentials: true

            - name: Set up Ruby
              uses: actions/setup-ruby@v1
              with:
                  ruby-version: "3.0"

            - name: Install dependencies
              run: |
                  gem install bundler
                  bundle install

            - name: Build site
              run: bundle exec jekyll build

            - name: Setup git config
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"

            - name: Deploy to GitHub Pages
              run: |
                  git checkout -b gh-pages || git checkout gh-pages
                  git pull origin gh-pages || true
                  cp -r _site/* .
                  git add .
                  git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
                  git push origin gh-pages
